export interface CourseInfo {
    id: number,
    ccName: string,
    cc: string,
    location: string,
    hole: number,
    course1: number,
    course2: number,
    courseName1: string,
    courseName2: string,
    courseDifficulty: number,
    greenDifficulty: number,
}

export const courseList: CourseInfo[] = [
    {
        id: 1,
        ccName: '지산 CC(동/남)',
        cc: 'jisan',
        location: '경기도',
        hole: 18,
        course1: 3,
        course2: 2,
        courseName1: '동',
        courseName2: '남',
        courseDifficulty: 4,
        greenDifficulty: 3,
    },
    {
        id: 2,
        ccName: '지산 CC(남/서)',
        cc: 'jisan',
        location: '경기도',
        hole: 18,
        course1: 2,
        course2: 4,
        courseName1: '남',
        courseName2: '서',
        courseDifficulty: 4,
        greenDifficulty: 3,
    },
    {
        id: 3,
        ccName: '지산 CC(서/동)',
        cc: 'jisan',
        location: '경기도',
        hole: 18,
        course1: 4,
        course2: 3,
        courseName1: '서',
        courseName2: '동',
        courseDifficulty: 4,
        greenDifficulty: 3,
    },
    {
        id: 4,
        ccName: '해운대 CC(실크/골든)',
        cc: 'haeundae',
        location: '경상남도',
        hole: 18,
        course1: 2,
        course2: 3,
        courseName1: '실크',
        courseName2: '골든',
        courseDifficulty: 5,
        greenDifficulty: 4,
    },
    {
        id: 5,
        ccName: '해운대 CC(로얄/실크)',
        cc: 'haeundae',
        location: '경상남도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: '로얄',
        courseName2: '실크',
        courseDifficulty: 5,
        greenDifficulty: 4,
    },
    {
        id: 6,
        ccName: '해운대 CC(골든/로얄)',
        cc: 'haeundae',
        location: '경상남도',
        hole: 18,
        course1: 3,
        course2: 1,
        courseName1: '골든',
        courseName2: '로얄',
        courseDifficulty: 5,
        greenDifficulty: 4,
    },
    {
        id: 7,
        ccName: '엠스클럽 의성(챔피언/마스터)',
        cc: 'haeundae',
        location: '경상남도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: '챔피언',
        courseName2: '마스터',
        courseDifficulty: 4.5,
        greenDifficulty: 4,
    }, {
        id: 8,
        ccName: '엠스클럽 의성(마스터/챌린저)',
        cc: 'haeundae',
        location: '경상남도',
        hole: 18,
        course1: 2,
        course2: 3,
        courseName1: '마스터',
        courseName2: '챌린저',
        courseDifficulty: 4,
        greenDifficulty: 4.5,
    }, {
        id: 9,
        ccName: '엠스클럽 의성(챌린저/챔피언)',
        cc: 'haeundae',
        location: '경상남도',
        hole: 18,
        course1: 3,
        course2: 1,
        courseName1: '챌린저',
        courseName2: '챔피언',
        courseDifficulty: 4.5,
        greenDifficulty: 4,
    }, { 
        id: 19,
        ccName: '무안CC(Out/In)',
        cc: 'muan',
        location: '전라남도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: 'Out',
        courseName2: 'In',
        courseDifficulty: 4.5,
        greenDifficulty: 3.5,
    }, { 
        id: 29,
        ccName: '부산 CC(Out/In)',
        cc: 'busan',
        location: '경상남도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: 'Out',
        courseName2: 'In',
        courseDifficulty: 4,
        greenDifficulty: 2,
    }, {
        id: 31,
        ccName: '알펜시아 700GC(알프스/아시아)',
        cc: 'alpensia',
        location: '강원도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: '알프스',
        courseName2: '아시아',
        courseDifficulty: 3,
        greenDifficulty: 2.5,
    }, { 
        id: 38,
        ccName: '핀크스 GC(동/서)',
        cc: 'pinx',
        location: '제주도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: '동',
        courseName2: '서',
        courseDifficulty: 4,
        greenDifficulty: 2.5,
    }, { 
        id: 39,
        ccName: '핀크스 GC(서/북)',
        cc: 'pinx',
        location: '제주도',
        hole: 18,
        course1: 2,
        course2: 3,
        courseName1: '서',
        courseName2: '북',
        courseDifficulty: 4,
        greenDifficulty: 2.5,
    },  { 
        id: 40,
        ccName: '핀크스 GC(북/동)',
        cc: 'pinx',
        location: '제주도',
        hole: 18,
        course1: 3,
        course2: 1,
        courseName1: '북',
        courseName2: '동',
        courseDifficulty: 2,
        greenDifficulty: 2.5,
    }, { 
        id: 45,
        ccName: '로얄 링스(퀸즈Out/퀸즈In)',
        cc: 'royallinks',
        location: '충청남도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: '퀸즈Out',
        courseName2: '퀸즈In',
        courseDifficulty: 2,
        greenDifficulty: 3,
    }, { 
        id: 47,
        ccName: '신원(솔로몬/에벤에셀)',
        cc: 'shinwon',
        location: '경기도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: '솔로몬',
        courseName2: '에벤에셀',
        courseDifficulty: 2.5,
        greenDifficulty: 2.5,
    }, { 
        id: 48,
        ccName: '신원(에벤에셀/데이비드)',
        cc: 'shinwon',
        location: '경기도',
        hole: 18,
        course1: 2,
        course2: 3,
        courseName1: '에벤에셀',
        courseName2: '데이비드',
        courseDifficulty: 3.5,
        greenDifficulty: 3,
    }, { 
        id: 49,
        ccName: '신원(데이비드/솔로몬)',
        cc: 'shinwon',
        location: '경기도',
        hole: 18,
        course1: 3,
        course2: 1,
        courseName1: '데이비드',
        courseName2: '솔로몬',
        courseDifficulty: 4,
        greenDifficulty: 3,
    }, { 
        id: 50,
        ccName: '코스카(메이플/릴리)',
        cc: 'kosca',
        location: '충청북도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: '메이플',
        courseName2: '릴리',
        courseDifficulty: 2.5,
        greenDifficulty: 3.5,
    }, { 
        id: 51,
        ccName: '코스카(릴리/파인)',
        cc: 'kosca',
        location: '충청북도',
        hole: 18,
        course1: 2,
        course2: 3,
        courseName1: '릴리',
        courseName2: '파인',
        courseDifficulty: 3.5,
        greenDifficulty: 3,
    }, { 
        id: 52,
        ccName: '코스카(파인/메이플)',
        cc: 'kosca',
        location: '충청북도',
        hole: 18,
        course1: 3,
        course2: 1,
        courseName1: '파인',
        courseName2: '메이플',
        courseDifficulty: 4,
        greenDifficulty: 3,
    }, { 
        id: 53,
        ccName: '태광(Out/In)',
        cc: 'taekwang',
        location: '경기도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: 'Out',
        courseName2: 'In',
        courseDifficulty: 3,
        greenDifficulty: 3,
    }, { 
        id: 54,
        ccName: '가야(신어/낙동)',
        cc: 'gaya',
        location: '경상남도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: '신어',
        courseName2: '낙동',
        courseDifficulty: 4,
        greenDifficulty: 2.5,
    }, { 
        id: 55,
        ccName: '인터불고(스카이/마운틴)',
        cc: 'interburgo',
        location: '경상북도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: '스카이',
        courseName2: '마운틴',
        courseDifficulty: 4,
        greenDifficulty: 5,
    }, { 
        id: 56,
        ccName: '인터불고(마운틴/벨리)',
        cc: 'interburgo',
        location: '경상북도',
        hole: 18,
        course1: 2,
        course2: 3,
        courseName1: '마운틴',
        courseName2: '벨리',
        courseDifficulty: 4,
        greenDifficulty: 5,
    }, { 
        id: 57,
        ccName: '인터불고(벨리/스카이)',
        cc: 'interburgo',
        location: '경상북도',
        hole: 18,
        course1: 3,
        course2: 2,
        courseName1: '벨리',
        courseName2: '스카이',
        courseDifficulty: 4,
        greenDifficulty: 5,
    }, { 
        id: 59,
        ccName: '아난티 남해(Out/In)',
        cc: 'anantinamhae',
        location: '경상남도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: 'Out',
        courseName2: 'In',
        courseDifficulty: 4,
        greenDifficulty: 5,
    }, { 
        id: 64,
        ccName: '썬힐(Out/In)',
        cc: 'sunhill',
        location: '경기도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: 'Out',
        courseName2: 'In',
        courseDifficulty: 2,
        greenDifficulty: 5,
    }, { 
        id: 78,
        ccName: '남서울 CC(Out/In)',
        cc: 'namseoul',
        location: '경기도',
        hole: 18,
        course1: 1,
        course2: 2,
        courseName1: 'Out',
        courseName2: 'In',
        courseDifficulty: 3,
        greenDifficulty: 4,
    },
     

]

